[theme]
primaryColor = "#BF5700"  # UT Tyler Orange (PMS 159)
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#003F87"  # UT Tyler Blue (PMS 294)
font = "sans serif"

[server]
headless = true
